import inspect as inspect
import itertools as itertools
from collections.abc import Callable, Container, Hashable, Iterable, Iterator, Mapping
from functools import reduce as reduce
from operator import and_ as and_operator
from operator import or_ as or_operator
from typing import ClassVar, TypeAlias, TypeVar

import boolean.boolean as _boolean

_ValueT = TypeVar("_ValueT")
_Token: TypeAlias = tuple[int | Symbol, str, object]
_Ast: TypeAlias = list[_Ast | type[Function] | Expression | int | None]
_Precedence: TypeAlias = Mapping[type[Function] | int, int]

TRACE_PARSE: bool

TOKEN_AND: int
TOKEN_OR: int
TOKEN_NOT: int
TOKEN_LPAR: int
TOKEN_RPAR: int
TOKEN_TRUE: int
TOKEN_FALSE: int
TOKEN_SYMBOL: int
TOKEN_TYPES: dict[int, str]

PARSE_UNKNOWN_TOKEN: int
PARSE_UNBALANCED_CLOSING_PARENS: int
PARSE_INVALID_EXPRESSION: int
PARSE_INVALID_NESTING: int
PARSE_INVALID_SYMBOL_SEQUENCE: int
PARSE_INVALID_OPERATOR_SEQUENCE: int
PARSE_ERRORS: dict[int, str]

class ParseError(Exception):
    token_type: int | Symbol | None
    token_string: str
    position: object
    error_code: int
    def __init__(
        self,
        token_type: int | Symbol | None = None,
        token_string: str = "",
        position: object = -1,
        error_code: int = 0,
    ) -> None: ...
    def __str__(self, *args: object, **kwargs: object) -> str: ...

class BooleanAlgebra:
    TRUE: BaseElement
    FALSE: BaseElement
    NOT: type[_boolean.NOT]
    AND: type[_boolean.AND]
    OR: type[_boolean.OR]
    Symbol: type[_boolean.Symbol]
    allowed_in_token: Container[str]
    def __init__(
        self,
        TRUE_class: type[BaseElement] | None = None,
        FALSE_class: type[BaseElement] | None = None,
        Symbol_class: type[_boolean.Symbol] | None = None,
        NOT_class: type[_boolean.NOT] | None = None,
        AND_class: type[_boolean.AND] | None = None,
        OR_class: type[_boolean.OR] | None = None,
        allowed_in_token: Container[str] = (".", ":", "_"),
    ) -> None: ...
    def definition(
        self,
    ) -> tuple[
        BaseElement,
        BaseElement,
        type[_boolean.NOT],
        type[_boolean.AND],
        type[_boolean.OR],
        type[_boolean.Symbol],
    ]: ...
    def symbols(self, *args: object) -> tuple[_boolean.Symbol, ...]: ...
    def parse(
        self,
        expr: str | Iterable[_Token],
        simplify: bool = False,
    ) -> Expression: ...
    def _start_operation(
        self,
        ast: _Ast,
        operation: type[Function],
        precedence: _Precedence,
    ) -> _Ast: ...
    def tokenize(self, expr: str) -> Iterator[_Token]: ...
    def _recurse_distributive(
        self, expr: Expression, operation_inst: DualBase
    ) -> Expression: ...
    def normalize(
        self,
        expr: Expression,
        operation: type[_boolean.AND] | type[_boolean.OR],
    ) -> Expression: ...
    def cnf(self, expr: Expression) -> Expression: ...
    def conjunctive_normal_form(self, expr: Expression) -> Expression: ...
    def dnf(self, expr: Expression) -> Expression: ...
    def disjunctive_normal_form(self, expr: Expression) -> Expression: ...

class Expression:
    TRUE: ClassVar[BaseElement | None]
    FALSE: ClassVar[BaseElement | None]
    NOT: ClassVar[type[_boolean.NOT] | None]
    AND: ClassVar[type[_boolean.AND] | None]
    OR: ClassVar[type[_boolean.OR] | None]
    Symbol: ClassVar[type[_boolean.Symbol] | None]
    sort_order: int | None
    args: tuple[Expression, ...]
    isliteral: bool
    iscanonical: bool
    def __init__(self) -> None: ...
    @property
    def objects(self) -> set[Hashable]: ...
    def get_literals(self) -> list[Expression]: ...
    @property
    def literals(self) -> set[Expression]: ...
    def literalize(self) -> Expression: ...
    def get_symbols(self) -> list[_boolean.Symbol]: ...
    @property
    def symbols(self) -> set[_boolean.Symbol]: ...
    def subs(
        self,
        substitutions: Mapping[Expression, Expression],
        default: Expression | None = None,
        simplify: bool = False,
    ) -> Expression: ...
    def _subs(
        self,
        substitutions: Mapping[Expression, Expression],
        default: Expression | None,
        simplify: bool,
    ) -> Expression | None: ...
    def simplify(self) -> Expression: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __and__(self, other: Expression) -> _boolean.AND: ...
    def __mul__(self, other: Expression) -> _boolean.AND: ...
    def __invert__(self) -> _boolean.NOT: ...
    def __or__(self, other: Expression) -> _boolean.OR: ...
    def __add__(self, other: Expression) -> _boolean.OR: ...
    def __bool__(self) -> bool: ...
    def __nonzero__(self) -> bool: ...

class BaseElement(Expression):
    dual: BaseElement
    def __init__(self) -> None: ...
    def __lt__(self, other: object) -> bool: ...
    def __nonzero__(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def pretty(self, indent: int = 0, debug: bool = False) -> str: ...

class _TRUE(BaseElement):
    def __init__(self) -> None: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __call__(self) -> _TRUE: ...
    def __nonzero__(self) -> bool: ...
    def __bool__(self) -> bool: ...

class _FALSE(BaseElement):
    def __init__(self) -> None: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __call__(self) -> _FALSE: ...
    def __nonzero__(self) -> bool: ...
    def __bool__(self) -> bool: ...

class Symbol(Expression):
    obj: object
    def __init__(self, obj: object) -> None: ...
    def __call__(self, **kwargs: _ValueT) -> _ValueT: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def pretty(self, indent: int = 0, debug: bool = False) -> str: ...

class Function(Expression):
    operator: str | None
    def __init__(self, *args: Expression) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def pretty(self, indent: int = 0, debug: bool = False) -> str: ...

class NOT(Function):
    def __init__(self, arg1: Expression) -> None: ...
    def literalize(self) -> Expression: ...
    def simplify(self) -> Expression: ...
    def cancel(self) -> Expression: ...
    def demorgan(self) -> Expression: ...
    def __call__(self, **kwargs: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def pretty(self, indent: int = 1, debug: bool = False) -> str: ...

class DualBase(Function):
    _pyoperator: ClassVar[Callable[[object, object], object] | None]
    identity: BaseElement
    annihilator: BaseElement
    dual: type[DualBase]
    def __init__(
        self, arg1: Expression, arg2: Expression, *args: Expression
    ) -> None: ...
    def __contains__(self, expr: object) -> bool: ...
    def simplify(self, sort: bool = True) -> Expression: ...
    def flatten(self) -> DualBase: ...
    def absorb(self, args: Iterable[Expression]) -> list[Expression]: ...
    def subtract(self, expr: Expression, simplify: bool) -> Expression | None: ...
    def distributive(self) -> Expression: ...
    def __lt__(self, other: object) -> bool: ...
    def __call__(self, **kwargs: _ValueT) -> _ValueT: ...

class AND(DualBase):
    def __init__(
        self, arg1: Expression, arg2: Expression, *args: Expression
    ) -> None: ...

class OR(DualBase):
    def __init__(
        self, arg1: Expression, arg2: Expression, *args: Expression
    ) -> None: ...
