# The bundled test module does not define a supported library API.

import unittest

class BooleanAlgebraTestCase(unittest.TestCase):
    def test_creation(self) -> None: ...
    def test_parse_with_mixed_operators_multilines_and_custom_symbol(self) -> None: ...
    def test_parse_recognizes_trueish_and_falsish_symbol_tokens(self) -> None: ...
    def test_parse_can_use_iterable_from_alternative_tokenizer(self) -> None: ...
    def test_parse_error_supports_custom_token_position(self) -> None: ...
    def test_parse_with_advanced_tokenizer_example(self) -> None: ...
    def test_allowing_additional_characters_in_tokens(self) -> None: ...
    def test_parse_raise_ParseError1(self) -> None: ...
    def test_parse_raise_ParseError2(self) -> None: ...
    def test_parse_raise_ParseError3(self) -> None: ...
    def test_parse_raise_ParseError4(self) -> None: ...
    def test_parse_raise_ParseError5(self) -> None: ...
    def test_parse_raise_ParseError6(self) -> None: ...
    def test_parse_raise_ParseError7(self) -> None: ...
    def test_parse_raise_ParseError8(self) -> None: ...
    def test_parse_raise_ParseError9(self) -> None: ...
    def test_parse_side_by_side_symbols_should_raise_exception_but_not(
        self,
    ) -> None: ...
    def test_parse_side_by_side_symbols_should_raise_exception_but_not2(
        self,
    ) -> None: ...
    def test_parse_side_by_side_symbols_raise_exception(self) -> None: ...
    def test_parse_side_by_side_symbols_with_parens_raise_exception(self) -> None: ...

class BaseElementTestCase(unittest.TestCase):
    def test_creation(self) -> None: ...
    def test_literals(self) -> None: ...
    def test_literalize(self) -> None: ...
    def test_simplify(self) -> None: ...
    def test_simplify_two_algebra(self) -> None: ...
    def test_dual(self) -> None: ...
    def test_equality(self) -> None: ...
    def test_order(self) -> None: ...
    def test_printing(self) -> None: ...

class SymbolTestCase(unittest.TestCase):
    def test_init(self) -> None: ...
    def test_isliteral(self) -> None: ...
    def test_literals(self) -> None: ...
    def test_literalize(self) -> None: ...
    def test_simplify(self) -> None: ...
    def test_simplify_different_instances(self) -> None: ...
    def test_equal_symbols(self) -> None: ...
    def test_order(self) -> None: ...
    def test_printing(self) -> None: ...

class NOTTestCase(unittest.TestCase):
    def test_init(self) -> None: ...
    def test_isliteral(self) -> None: ...
    def test_literals(self) -> None: ...
    def test_literalize(self) -> None: ...
    def test_simplify(self) -> None: ...
    def test_cancel(self) -> None: ...
    def test_demorgan(self) -> None: ...
    def test_order(self) -> None: ...
    def test_printing(self) -> None: ...

class DualBaseTestCase(unittest.TestCase):
    maxDiff: int | None
    def test_init(self) -> None: ...
    def test_isliteral(self) -> None: ...
    def test_literals(self) -> None: ...
    def test_literalize(self) -> None: ...
    def test_annihilator(self) -> None: ...
    def test_identity(self) -> None: ...
    def test_dual(self) -> None: ...
    def test_simplify(self) -> None: ...
    def test_absorption_invariant_to_order(self) -> None: ...
    def test_parse_complex_expression_should_create_same_expression_as_python(
        self,
    ) -> None: ...
    def test_simplify_complex_expression_parsed_with_simplify(self) -> None: ...
    def test_complex_expression_without_parens_parsed_or_built_in_python_should_be_identical(
        self,
    ) -> None: ...
    def test_simplify_complex_expression_parsed_then_simplified(self) -> None: ...
    def test_parse_invalid_nested_and_should_raise_a_proper_exception(self) -> None: ...
    def test_subtract(self) -> None: ...
    def test_flatten(self) -> None: ...
    def test_distributive(self) -> None: ...
    def test_equal(self) -> None: ...
    def test_order(self) -> None: ...
    def test_printing(self) -> None: ...

class OtherTestCase(unittest.TestCase):
    def test_class_order(self) -> None: ...
    def test_parse(self) -> None: ...
    def test_subs(self) -> None: ...
    def test_subs_default(self) -> None: ...
    def test_normalize(self) -> None: ...
    def test_get_literals_return_all_literals_in_original_order(self) -> None: ...
    def test_get_symbols_return_all_symbols_in_original_order(self) -> None: ...
    def test_literals_return_set_of_unique_literals(self) -> None: ...
    def test_literals_and_negation(self) -> None: ...
    def test_symbols_and_negation(self) -> None: ...
    def test_objects_return_set_of_unique_Symbol_objs(self) -> None: ...
    def test_normalize_blowup(self) -> None: ...

class BooleanBoolTestCase(unittest.TestCase):
    def test_bool(self) -> None: ...

class CustomSymbolTestCase(unittest.TestCase):
    def test_custom_symbol(self) -> None: ...

class CallabilityTestCase(unittest.TestCase):
    def test_and(self) -> None: ...
    def test_or(self) -> None: ...
    def test_not(self) -> None: ...
    def test_symbol(self) -> None: ...
    def test_composite(self) -> None: ...
    def test_negate_A_or_B(self) -> None: ...
